apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
spec:
  replicas: 3
  template:
    metadata:
      name: api-gateway-pod
      labels:
        app: api-gateway-pod
    spec:
      containers:
        - name: api-gateway-container
          image: nimpi/apigateway:latest
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      app: api-gateway-pod