apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-deployment
spec:
  replicas: 3
  template:
    metadata:
      name: front-end-pod
      labels:
        app: front-end-pod
    spec:
      containers:
        - name: front-end-container
          image: nimpi/front-end:latest
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      app: front-end-pod